volumes:
  frontend_node_modules:

services:
  db:
    image: postgres:18
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "8000:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d

  ingestion:
    build:
      context: ../script
      dockerfile: Dockerfile
    container_name: ingestion_container
    environment:
      - PG_HOST=${POSTGRES_HOST}
      - PG_DB=${POSTGRES_DB}
      - PG_USER=${POSTGRES_USER}
      - PG_PW=${POSTGRES_PASSWORD}
      - PG_PORT=${POSTGRES_PORT}
      - TMDB_API_ACCESS_TOKEN=${TMDB_API_ACCESS_TOKEN}
    entrypoint: 
      [
        "/bin/sh", 
        "-c", 
        "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"
      ]
    volumes:
      - ../script:/app

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend_container
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:${FRONTEND_PORT}
      - OMDB_API_ACCESS_TOKEN=${OMDB_API_ACCESS_TOKEN}
      - TMDB_API_ACCESS_TOKEN=${TMDB_API_ACCESS_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${BACKEND_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - DB_PORT=${POSTGRES_PORT}
      - DB_HOST=${POSTGRES_HOST}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    entrypoint: 
      [
        "/bin/sh", 
        "-c", 
        "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"
      ]
    depends_on:
      - ingestion
    working_dir: /app
    volumes:
      - ../backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    environment:
      - VITE_BACKEND_BASE=http://localhost:${BACKEND_PORT}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    entrypoint: 
      [
        "/bin/sh", 
        "-c", 
        "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"
      ]
    depends_on:
      - backend
    working_dir: /app
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules